name: Changelog Workflow
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  changelog:
    permissions: write-all
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get PR information
        id: pr-info
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}" | tr -d '\n')
          PR_OWNER=$(echo "${{ github.event.pull_request.head.repo.owner.login }}" | tr -d '\n')
          PR_REPO=$(echo "${{ github.event.pull_request.head.repo.name }}" | tr -d '\n')
          PR_API_URL="https://api.github.com/repos/${PR_OWNER}/${PR_REPO}/pulls/${PR_NUMBER}/reviews?per_page=100&page=1"
          PR_REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$PR_API_URL")
          echo "::set-env name=PR_REVIEWS::$PR_REVIEWS"

      - name: Check if PR is approved
        run: |
          # Get the PR status from the API response
          PR_STATUS=$(echo "${{ steps.pr-info.outputs.reviews }}" | jq -r '.[].state')
          # Check if the PR is approved
          if echo "$PR_STATUS" | grep -q "APPROVED"; then
            echo "PR is approved"
          else
            # If the PR is not approved
            echo "PR is not approved yet. Exiting..."
            exit 1
          fi
      - name: Check if tag exists from package.json version # check if tag from package.json version already exists
        run: |
          # Get the package version from package.json
          PACKAGE_VERSION=$(jq -r '.version' package.json)

          # Check if a tag with the current version exists
          if git rev-parse "refs/tags/v${PACKAGE_VERSION}" >/dev/null 2>&1; then
            echo "The tag with the version v$PACKAGE_VERSION already exists"
            exit 1
          else
            # If no tag exists
            echo "The tag does not exist"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: setup git config
        run: |
          git config user.name "Autorelease Bot"
          git config user.email "<>"
      - name: Pubish Release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
        run: |
          yarn changelog
          git add CHANGELOG.md
          git commit -m "chore(pre-release): v${{ steps.package-version.outputs.current-version }} CHANGELOG"
          git push origin HEAD:${{ github.head_ref }} --no-verify
