name: Changelog Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  changelog:
    permissions: write-all
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn
      - name: setup git config
        run: |
          git config user.name "Autorelease Bot"
          git config user.email "<>"
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Check for existing tag
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
      - name: Pubish Release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        run: |
          yarn changelog
          git add CHANGELOG.md
          git commit -m "chore(release): v${{ steps.package-version.outputs.current-version }} 🚀 [skip-ci]"
          git push origin --no-verify
